version: "3"

services:
  jenkins:
    # image: jenkins/jenkins:jdk11
    build: .
    container_name: jenkins
    environment:
      - JENKINS_ADMIN_NAME=${JENKINS_ADMIN_NAME}
      - JENKINS_ADMIN_PASS=${JENKINS_ADMIN_PASS}
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: on-failure

volumes:
  jenkins_home: